# Generated by Django 3.0.6 on 2020-06-06 11:38

import Profile.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('created_on', models.DateField(default=datetime.date.today)),
                ('type', models.CharField(choices=[('Family', 'Family'), ('Friends', 'Friends'), ('Business', 'Business'), ('Society', 'Society')], default=Profile.models.groupType['Family'], max_length=10)),
                ('adm_settings', models.CharField(choices=[('Admin', 'Admin only'), ('Everyone', 'Everyone')], default=Profile.models.adm['Everyone'], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=17)),
                ('location', models.CharField(blank=True, default='Blank', max_length=30)),
                ('key', models.CharField(blank=True, max_length=100, unique=True)),
                ('enable_authenticator', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='group_Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_on', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.group')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.Profile'),
        ),
    ]
