# Generated by Django 3.0.6 on 2020-06-14 12:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file', models.CharField(max_length=50)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('time_created', models.TimeField(default=django.utils.timezone.now)),
                ('json_data', jsonfield.fields.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(max_length=30, null=True)),
                ('order_id', models.CharField(max_length=20, null=True)),
                ('customer_id', models.CharField(max_length=15, null=True)),
                ('date_issue', models.CharField(max_length=12, null=True)),
                ('amount_total', models.FloatField(null=True)),
                ('amount_due', models.FloatField(null=True)),
                ('sender_name', models.CharField(max_length=30, null=True)),
                ('sender_address', models.CharField(max_length=200, null=True)),
                ('sender_vat_id', models.CharField(max_length=30, null=True)),
                ('recipient_name', models.CharField(max_length=30, null=True)),
                ('recipient_address', models.CharField(max_length=200, null=True)),
                ('item_description', models.CharField(max_length=150, null=True)),
                ('rawdata', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='docdata.RawData')),
            ],
        ),
    ]
