# Generated by Django 3.0.6 on 2020-06-17 05:49

from django.db import migrations, models
import django.db.models.deletion
import json_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
        ('docdata', '0002_billdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billdata',
            name='user',
        ),
        migrations.RemoveField(
            model_name='processeddata',
            name='item_description',
        ),
        migrations.AddField(
            model_name='processeddata',
            name='all_items',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='rawdata',
            name='device_transfer',
            field=json_field.fields.JSONField(default='null', help_text='Enter a valid JSON object', null=True),
        ),
        migrations.AddField(
            model_name='rawdata',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Profile.Profile'),
        ),
        migrations.AlterField(
            model_name='processeddata',
            name='amount_due',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='processeddata',
            name='amount_total',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='json_data',
            field=json_field.fields.JSONField(default='null', help_text='Enter a valid JSON object'),
        ),
    ]
