# Generated by Django 3.0.6 on 2020-06-17 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docdata', '0003_auto_20200617_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50, null=True)),
                ('item_quantity', models.CharField(max_length=10, null=True)),
                ('item_total_amount', models.CharField(max_length=10, null=True)),
                ('rawdata', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='docdata.RawData')),
            ],
        ),
    ]
