# Generated by Django 3.0.6 on 2020-06-23 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
        ('docdata', '0004_billitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BillData',
            new_name='GroupDataLink',
        ),
    ]
